export enum LoaderSettingKeyName {
  ValidateOnly = 'ValidateOnly',
  FileFormat = 'FileFormat',
  // Pricings
  PricingsSheetName = 'PricingsSheetName',
  PricingNotesSheetName = 'PricingNotesSheetName',
  // MRP Fields
  PricingsBaseMRP = 'PricingsBaseMRP',
  PricingsTCCMRP = 'PricingsTCCMRP',
  PricingsBonusMRP = 'PricingsBonusMRP',
  PricingsTCCTargetMRP = 'PricingsTCCTargetMRP',
  PricingsLTIPMRP = 'PricingsLTIPMRP',
  PricingsTDCMRP = 'PricingsTDCMRP',
  PricingsAllowMRP = 'PricingsAllowMRP',
  PricingsFixedMRP = 'PricingsFixedMRP',
  PricingsRemunMRP = 'PricingsRemunMRP',
  PricingsTGPMRP = 'PricingsTGPMRP',
  PricingsBonusPctMRP = 'PricingsBonusPctMRP',
  PricingsBonusTargetMRP = 'PricingsBonusTargetMRP',
  PricingsBonusTargetPctMRP = 'PricingsBonusTargetPctMRP',
  PricingsTargetLTIPMRP = 'PricingsTargetLTIPMRP',
  PricingsTargetTDCMRP = 'PricingsTargetTDCMRP',
  PricingsSalesIncentiveTargetMRP = 'PricingsSalesIncentiveTargetMRP',
  PricingsSalesIncentiveActualMRP = 'PricingsSalesIncentiveActualMRP',
  PricingsLTIPPctMRP = 'PricingsLTIPPctMRP',
  PricingsSalesIncentiveTargetPctMRP = 'PricingsSalesIncentiveTargetPctMRP',
  PricingsSalesIncentiveActualPctMRP = 'PricingsSalesIncentiveActualPctMRP',
  PricingsTCCTargetPlusAllowNoCarMRP = 'PricingsTCCTargetPlusAllowNoCarMRP',
  PricingsTCCTargetPlusAllowMRP = 'PricingsTCCTargetPlusAllowMRP',
  PricingsTCCPlusAllowNoCarMRP = 'PricingsTCCPlusAllowNoCarMRP',
  PricingsTCCPlusAllowMRP = 'PricingsTCCPlusAllowMRP',
  // Adjustments
  PricingsMatchWeight = 'PricingsMatchWeight',
  PricingsCompositeAdj = 'PricingsCompositeAdj',
  PricingsAging = 'PricingsAging',
  PricingsMatchAdj = 'PricingsMatchAdjustment'
}
