export const environment = {
  avatarSource: 'https://qa00filestore001.blob.core.windows.net/publicfiles/avatars/',
  companyLogoSource: 'https://qa00filestore001.blob.core.windows.net/publicfiles/company_logos/',
  cloudFilesPublicBaseUrl: 'https://qa00filestore001.blob.core.windows.net/publicfiles/',
  marketingImageSource: 'https://qa00filestore001.blob.core.windows.net/publicfiles/marketing_image/',
  production: true,
  payfactorsApiUrl: '/odata/',
  payfactorsMarketDataUrl: '/marketdata/',
  userVoiceUrl: 'http://payfactors.uservoice.com/forums/',
  userVoiceLoginRedirect: '/payfactors/UserVoice/RedirectFromLogin',
  userVoiceForumId: 268517,
  ngAppRoot: '/ng/',
  tableauPayfactorsReportingServer: 'https://stagereports.payfactors.com/',
  defaultHomePage: '/client/dashboard',
  firstTimeLoginPage: '/client/auth/first-login',
  allowSelfRegistration: true,
  smallBusinessApiUrl: 'https://smallbiz.payfactors.com/api/',
  smallBusinessAppUrl: 'https://smallbiz.payfactors.com/app/',
  hostPath: 'client',
  allowHubspotRegistration: true,
  hubspotRegistrationUrl: 'https://info.payfactors.com/payfactors-free-market-data-wh',
  siteAdminUrl: '/client/pf-admin',
  companyAdminUrl: '/client/admin/company-admin',
  payfactorsFrontEndApiUrl: '/Payfactors/',
  name: 'staging'
};
