export const environment = {
  avatarSource: 'https://c49e5bcd31eb4648ab13-7621f32ad8fab3cdc08ded8807f92015.ssl.cf5.rackcdn.com/avatars/',
  companyLogoSource: 'https://c49e5bcd31eb4648ab13-7621f32ad8fab3cdc08ded8807f92015.ssl.cf5.rackcdn.com/company_logos/',
  cloudFilesPublicBaseUrl: 'https://c49e5bcd31eb4648ab13-7621f32ad8fab3cdc08ded8807f92015.ssl.cf5.rackcdn.com/',
  marketingImageSource: 'https://c49e5bcd31eb4648ab13-7621f32ad8fab3cdc08ded8807f92015.ssl.cf5.rackcdn.com/marketing_image/',
  production: true,
  payfactorsApiUrl: '/odata/',
  payfactorsMarketDataUrl: '/marketdata/',
  userVoiceUrl: 'http://payfactors.uservoice.com/forums/',
  userVoiceLoginRedirect: '/payfactors/UserVoice/RedirectFromLogin',
  userVoiceForumId: 268517,
  ngAppRoot: '/ng/',
  mapboxAccessToken: 'pk.eyJ1IjoicGZtYXBzIiwiYSI6ImNqaDk5bzgzYTAwa28zYXFrdjN5aG9jN2IifQ.cqCQzg8IyrwoKGrqb2wciA',
  tableauPayfactorsReportingServer: 'https://reports.payfactors.com/',
  tableauPublicReportingServer: 'https://public.tableau.com/',
  defaultHomePage: '/client/dashboard',
  firstTimeLoginPage: '/client/auth/first-login',
  allowSelfRegistration: true,
  smallBusinessApiUrl: 'https://smallbiz.payfactors.com/api/',
  smallBusinessAppUrl: 'https://smallbiz.payfactors.com/app/',
  hostPath: 'client',
  allowHubspotRegistration: true,
  hubspotRegistrationUrl: 'https://info.payfactors.com/payfactors-free-market-data',
  siteAdminUrl: '/client/pf-admin',
  companyAdminUrl: '/client/admin/company-admin',
  reCaptchaV3SiteKey: '6LfpysMUAAAAAD0gF6kO4idsRAdASCt474q6yrCd'
};
