export const environment = {
  avatarSource: 'https://f7021091349f6caaffd2-5b56effc7aa76a3323ddc3429496d092.ssl.cf5.rackcdn.com/avatars/',
  companyLogoSource: 'https://f7021091349f6caaffd2-5b56effc7aa76a3323ddc3429496d092.ssl.cf5.rackcdn.com/company_logos/',
  cloudFilesPublicBaseUrl: 'https://f7021091349f6caaffd2-5b56effc7aa76a3323ddc3429496d092.ssl.cf5.rackcdn.com/',
  marketingImageSource: 'https://f7021091349f6caaffd2-5b56effc7aa76a3323ddc3429496d092.ssl.cf5.rackcdn.com/marketing_image/',
  production: false,
  payfactorsApiUrl: '/odata/',
  payfactorsMarketDataUrl: '/marketdata/',
  userVoiceUrl: 'http://payfactors.uservoice.com/forums/',
  userVoiceLoginRedirect: '/payfactors/UserVoice/RedirectFromLogin',
  userVoiceForumId: 268517,
  ngAppRoot: '/ng/',
  mapboxAccessToken: 'pk.eyJ1IjoianByZWhlbW9wZiIsImEiOiJjajh1a3VqZDMxMmt0MzRxenFsem9oaTN1In0.06ePvHZIgOD5IHAYad8JHQ',
  tableauPayfactorsReportingServer: 'https://stagereports.payfactors.com/',
  tableauPublicReportingServer: 'https://public.tableau.com/',
  defaultHomePage: '/client/dashboard',
  firstTimeLoginPage: '/client/auth/first-login',
  allowSelfRegistration: true,
  smallBusinessApiUrl: 'http://smallbizdev.payfactors.com/api/',
  smallBusinessAppUrl: 'http://smallbizdev.payfactors.com/app/',
  hostPath: 'client',
  allowHubspotRegistration: true,
  hubspotRegistrationUrl: 'https://info.payfactors.com/payfactors-free-market-data-wh',
  // /client/pf-admin ### /ng/site-admin
  siteAdminUrl: '/client/pf-admin',
  // /client/admin/company-admin ### /ng/company-admin
  companyAdminUrl: '/client/admin/company-admin',
  payfactorsFrontEndApiUrl: '/Payfactors/',
};
