export interface StatementsGridField {
  FieldName: string;
  DisplayName: string;
  DataType: string;
  Width?: number;
  CustomClass?: string;
}

export const statementsGridFields: StatementsGridField[] = [
  {
    FieldName: 'Name',
    DisplayName: 'Statement Name',
    DataType: 'string',
    Width: 300
  },
  {
    FieldName: 'CreatedBy',
    DisplayName: 'Created By',
    DataType: 'string'
  },
  {
    FieldName: 'CreatedDate',
    DisplayName: 'Created Date',
    DataType: 'date',
  },
  {
    FieldName: 'LastGeneratedDate',
    DisplayName: 'Last Generated',
    DataType: 'date',
  },
  {
    FieldName: 'LastGeneratedBy',
    DisplayName: 'Generated By',
    DataType: 'string',
  },
  {
    FieldName: 'Employees',
    DisplayName: 'Employees',
    DataType: 'int',
    Width: 120,
    CustomClass: 'text-right'
  }
];
