export enum TileNames {
  Activity = 'Activity',
  CompanyAdmin = 'Company Admin',
  DataInsights = 'Data Insights',
  Employees = 'Employees',
  Ideas = 'Ideas',
  InternationalData = 'International Data',
  JobDescriptions = 'Job Descriptions',
  Jobs = 'Jobs',
  NewCommunity = 'New Community',
  NewProject = 'New Project',
  PayMarkets = 'Pay Markets',
  Peer = 'Peer',
  PricingProjects = 'Pricing Projects',
  QuickPrice = 'Quick Price',
  Resources = 'Resources',
  Service = 'Service',
  Structures = 'Structures',
  Surveys = 'Surveys',
  TotalRewards = 'Total Rewards',
  WhatIsNew = 'What Is New'
}
