export interface StatementsGridField {
  FieldName: string;
  DisplayName: string;
  DataType: 'string' | 'date' | 'int';
  Width?: number;
}

export const statementsGridFields: StatementsGridField[] = [
  {
    FieldName: 'StatementName',
    DisplayName: 'Statement Name',
    DataType: 'string',
    Width: 300
  },
  {
    FieldName: 'GeneratedDate',
    DisplayName: 'Generated Date',
    DataType: 'date',
  },
  {
    FieldName: 'GeneratedBy',
    DisplayName: 'Generated By',
    DataType: 'string',
  },
  {
    FieldName: 'EmployeeCount',
    DisplayName: 'Assigned Employees',
    DataType: 'int'
  },
  {
    FieldName: 'DeliveryMethod',
    DisplayName: 'Delivery Method',
    DataType: 'string'
  }
];
