export enum JobDescriptionColumn {
    AppliesTo = 'AppliesTo',
    CreateDate = 'CreateDate',
    CreatedBy = 'CreatedBy',
    CurrentReviewer = 'CurrentReviewer',
    FLSAStatus = 'TemplateName',
    JobCode = 'JobCode',
    JobDescriptionStatus = 'JobDescriptionStatus',
    JobDescriptionTitle = 'JobDescriptionTitle',
    JobFamily = 'JobFamily',
    JobLevel = 'JobLevel',
    JobTitle = 'JobTitle',
    LastUpdatedDate = 'LastUpdatedDate',
    PublicView = 'PublicView',
    TemplateName = 'TemplateName',
    VersionNumber = 'VersionNumber',
}
