export enum TileTypes {
  Unknown = 'Unknown',
  DataInsights = 'DataInsights',
  Employees = 'Employees',
  JobDescriptions = 'JobDescriptions',
  MyJobs = 'MyJobs',
  PayMarkets = 'PayMarkets',
  Peer = 'Peer',
  PricingProjects = 'PricingProjects',
  Resources = 'Resources',
  Service = 'Service',
  Structures = 'Structures',
  Surveys = 'Surveys',
  DataDiagnostics = 'DataDiagnostics',
  Community = 'Community',
  NewCommunity = 'NewCommunity',
  Ideas = 'Ideas',
  QuickPrice = 'QuickPrice',
  TotalRewards = 'TotalRewards'
}
